before_script:
    - export GTEST_ROOT=/opt/gtest-1.8.0

image: docker pull rikorose/gcc-cmake

stages:
    - build

build-gcc:
    stage: build
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make -j2
      - make test