---

labels:
    hostname: ci-runner.server10.kruton.de

steps:
    build:
        image: chizeta/centos:8
        pull: true
        when:
            branch: [main, dev]
            event: [push, pull_request, manual]
        commands:
            - source /opt/rh/gcc-toolset-9/enable
            - source /etc/profile.d/modules.sh
            - module use --append /usr/share/modulefiles
            - module load mpi
            - chown -R test:test .
            - su test
            - mkdir build-gcc
            - cd build-gcc
            - cmake3 -DSCALAR_BUILD=on ..
            - make -j2
            - cd ..
            - mkdir build-clang
            - cd build-clang
            - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake3 -DSCALAR_BUILD=on ..
            - make -j2
            - cd ../build-gcc
            - make test
            - cd ../build-clang
            - make test
