---

steps:
    build:
        image: chizeta/centos:8
        pull: true
        user: test
        commands:
            - source /opt/rh/gcc-toolset-9/enable
            - source /etc/profile.d/modules.sh
            - module use --append /usr/share/modulefiles
            - module load mpi
            - whoami
            - mkdir build-gcc
            - cd build-gcc
            - cmake3 -DSCALAR_BUILD=on ..
            - make -j2
            - make test
            - cd ..
            - mkdir build-clang
            - cd build-clang
            - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake3 -DRUN_PIPELINE=on -DSCALAR_BUILD=on ..
            - make -j2
            - make test
