
#include "range_base.h"
#include "index_base.h"
#include "mrange.h"
#include "crange.h"
//#include "subrange.h"
//#include "value_range.h"
#include "xindex.h"
#include "yrange.h"
#include "dindex.h"
#include "lindex.h"
#include "index_mul.h"
#include "index_pack.h"
#include "index_format.h"

#include "ranges.cc.h"
