# This file is based on https://github.com/satu0king/Github-Documentation-With-Doxygen/blob/master/main.yml

name: Doxygen Action

# Trigger workflow only on pushed to master branch:
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile"
        # Working directory
        working-directory: "./doc/doxy"
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/doxy/html

permissions:
  contents: write
